DROP DATABASE IF EXISTS gotcars_db;
DROP USER IF EXISTS `USER_NAME`@`%`;
CREATE DATABASE IF NOT EXISTS gotcars_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `USER_NAME`@`%` IDENTIFIED WITH mysql_native_password BY 'PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `gotcars_db`.* TO `USER_NAME`@`%`;